version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Installing additional libraries
          command: |
            . venv/bin/activate
            pip install spacy
            python -m spacy download en_core_web_sm
            wget https://github.com/explosion/sense2vec/releases/download/v1.0.0/s2v_reddit_2015_md.tar.gz
            tar -xvf s2v_reddit_2015_md.tar.gz
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pip install pytest
            pytest tests
      - store_artifacts:
          path: test-reports/
          destination: python_app